---
blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/remoterabbit/conftest-policies/discussions
    about: For open-ended questions or design discussions, please use GitHub Discussions.
