#!/usr/bin/env bash
#
# Regenerate docs/changelogs/<domain>.md, one per policy/<domain>/ directory.
#
# release-please still owns the top-level CHANGELOG.md (release-cadence view).
# These per-domain files provide a "what changed for me?" view for consumers
# adopting only a single policy domain. Filtering is path-based: a commit is
# considered relevant to <domain> if it touched policy/<domain>/** or
# tests/fixtures/<domain>/**.
#
# Requires: git-cliff (https://git-cliff.org).

set -euo pipefail

OUT_DIR="docs/changelogs"
POLICY_DIR="policy"
FIXTURE_DIR="tests/fixtures"

if ! command -v git-cliff >/dev/null 2>&1; then
  echo "git-cliff is not installed. Install via 'cargo install git-cliff' or" \
       "download a release from https://github.com/orhun/git-cliff/releases." >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

# Discover policy domains as the top-level subdirectories of policy/.
mapfile -t domains < <(
  find "$POLICY_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort
)

if [[ ${#domains[@]} -eq 0 ]]; then
  echo "No policy domains found under $POLICY_DIR/" >&2
  exit 1
fi

# Index file.
{
  echo "# Per-domain changelogs"
  echo
  echo "<!-- DO NOT EDIT: regenerated by \`make changelogs\` from git history. -->"
  echo
  echo "Top-level releases live in [\`CHANGELOG.md\`](../../CHANGELOG.md)."
  echo "The files below are filtered, path-scoped views for consumers who only"
  echo "adopt a single policy domain."
  echo
  for d in "${domains[@]}"; do
    echo "- [\`$d\`](./$d.md)"
  done
} > "$OUT_DIR/README.md"

# Per-domain files.
for d in "${domains[@]}"; do
  echo "==> docs/changelogs/$d.md"
  git-cliff \
    --config cliff.toml \
    --include-path "$POLICY_DIR/$d/**" \
    --include-path "$FIXTURE_DIR/$d/**" \
    --output "$OUT_DIR/$d.md"
done
