#!/usr/bin/env bash
#
# Regenerate docs/changelogs/<domain>.md, one per policy/<domain>/ directory,
# plus a docs/changelogs/README.md index. Driven by git-cliff with the
# repo-root cliff.toml and --include-path filters.

set -euo pipefail

OUT_DIR="docs/changelogs"
POLICY_DIR="policy"
FIXTURE_DIR="tests/fixtures"

if ! command -v git-cliff >/dev/null 2>&1; then
  echo "git-cliff is not installed. See https://git-cliff.org/docs/installation" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

# Discover policy domains as the top-level subdirectories of policy/.
mapfile -t domains < <(
  find "$POLICY_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort
)

if [[ ${#domains[@]} -eq 0 ]]; then
  echo "No policy domains found under $POLICY_DIR/" >&2
  exit 1
fi

# Per-domain changelog files.
for d in "${domains[@]}"; do
  echo "==> $OUT_DIR/$d.md"
  git-cliff \
    --config cliff.toml \
    --include-path "$POLICY_DIR/$d/**" \
    --include-path "$FIXTURE_DIR/$d/**" \
    --output "$OUT_DIR/$d.md"

  # Normalize: strip trailing blank lines so pre-commit's end-of-file-fixer
  # (which collapses them to a single trailing newline) doesn't fight us in CI.
  printf '%s\n' "$(cat "$OUT_DIR/$d.md")" > "$OUT_DIR/$d.md"
done

# Index file listing all domain changelogs.
{
  echo "# Policy Changelogs"
  echo "<!-- DO NOT EDIT: regenerated by \`make changelogs\` from git history. -->"
  echo
  echo "Per-domain changelogs generated from git history via [git-cliff](https://git-cliff.org/)."
  echo "The top-level [CHANGELOG.md](../../CHANGELOG.md) is owned by release-please."
  echo
  for d in "${domains[@]}"; do
    echo "- [\`$d\`](./$d.md)"
  done
} > "$OUT_DIR/README.md"

printf '%s\n' "$(cat "$OUT_DIR/README.md")" > "$OUT_DIR/README.md"
