#!/usr/bin/env bash
# Generate docs/POLICIES.md from OPA METADATA annotations on every rule under
# policy/. The source of truth is the rego files; this script only renders.
#
# Requires: opa, jq

set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v opa >/dev/null 2>&1; then
  echo "error: opa not found on PATH (install: https://www.openpolicyagent.org/docs/latest/#running-opa)" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq not found on PATH" >&2
  exit 1
fi

mkdir -p docs
out=docs/POLICIES.md
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

opa inspect -a policy/ -f json >"$tmp"

{
  cat <<'EOF'
<!-- Generated by scripts/gen-docs.sh from OPA METADATA. Do not edit by hand. -->

# Policy reference

This page is generated from the `# METADATA` annotations on each rule. To
update it, edit the rego files under `policy/` and run `make docs`.

EOF

  # List packages first (scope = "package"), then their rules (scope = "rule").
  jq -r '
    def pkg_name(p): [ p[].value ] | .[1:] | join(".");

    # Build a map: package_name -> package_annotation
    ( [ .annotations[] | select(.annotations.scope == "package") ]
      | map({ key: pkg_name(.path), value: . })
      | from_entries ) as $pkgs

    # Group rules by their package (path minus last segment = package)
    | ( [ .annotations[] | select(.annotations.scope == "rule") ]
        | group_by( pkg_name(.path[:-1]) ) ) as $grouped

    | $grouped[] as $rules
    | (pkg_name($rules[0].path[:-1])) as $pkg
    | "## `\($pkg)`\n",
      ( $pkgs[$pkg] // {} | .annotations.description // "" | "\(.)\n" ),
      ( $rules[] |
        "### \(.annotations.title // (.path | last | .value))\n",
        (.annotations.description // "" | "\(.)"),
        (if .annotations.custom then
          "\n| | |\n|---|---|\n" +
          ( [ .annotations.custom | to_entries[]
              | "| **\(.key)** | \(.value | tostring | gsub("\n";" ")) |" ]
            | join("\n") ) + "\n"
         else "" end),
        "\n_Source: `\(.location.file):\(.location.row)`_\n"
      )
  ' "$tmp"
} >"$out"

# Normalize trailing newlines so end-of-file-fixer doesn't fight us:
# ensure exactly one newline at EOF.
content=$(<"$out")
printf '%s\n' "$content" >"$out"

echo "Wrote $out"
