#!/usr/bin/env bash
#
# Regenerate one docs/changelogs/<kind>.md file per policy kind (hcl, plan, ...)
# under policy/terraform/. The shared `lib` directory is excluded because it
# carries no consumer-facing policy.
#
# Each changelog is driven by git-cliff with the repo-root cliff.toml and
# --include-path filters that scope it to the matching policy + fixture paths.

set -euo pipefail

OUT_DIR="docs/changelogs"
POLICY_BASE="policy/terraform"
FIXTURE_BASE="tests/fixtures/terraform"
EXCLUDE_KINDS=("lib")

if ! command -v git-cliff >/dev/null 2>&1; then
  echo "git-cliff is not installed. See https://git-cliff.org/docs/installation" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

# Discover policy kinds (hcl, plan, ...) as the subdirectories of $POLICY_BASE/.
mapfile -t kinds < <(
  find "$POLICY_BASE" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort
)

# Filter excluded kinds.
filtered=()
for k in "${kinds[@]}"; do
  skip=
  for x in "${EXCLUDE_KINDS[@]}"; do
    [[ $k == "$x" ]] && skip=1 && break
  done
  [[ -z $skip ]] && filtered+=("$k")
done
kinds=("${filtered[@]}")

if [[ ${#kinds[@]} -eq 0 ]]; then
  echo "No policy kinds found under $POLICY_BASE/" >&2
  exit 1
fi

# Per-kind changelog files.
for k in "${kinds[@]}"; do
  echo "==> $OUT_DIR/$k.md"
  git-cliff \
    --config cliff.toml \
    --include-path "$POLICY_BASE/$k/**" \
    --include-path "$FIXTURE_BASE/$k/**" \
    --output "$OUT_DIR/$k.md"

  # Normalize: strip trailing blank lines so pre-commit's end-of-file-fixer
  # (which collapses them to a single trailing newline) doesn't fight us in CI.
  printf '%s\n' "$(cat "$OUT_DIR/$k.md")" > "$OUT_DIR/$k.md"
done

# Index file listing all per-kind changelogs.
{
  echo "# Policy Changelogs"
  echo "<!-- DO NOT EDIT: regenerated by \`make changelogs\` from git history. -->"
  echo
  echo "Per-kind changelogs generated from git history via [git-cliff](https://git-cliff.org/),"
  echo "one file per top-level policy kind under \`$POLICY_BASE/\`."
  echo "The top-level [CHANGELOG.md](../../CHANGELOG.md) is owned by release-please."
  echo
  for k in "${kinds[@]}"; do
    echo "- [\`$k\`](./$k.md) - \`$POLICY_BASE/$k/\` and \`$FIXTURE_BASE/$k/\`"
  done
} > "$OUT_DIR/README.md"

printf '%s\n' "$(cat "$OUT_DIR/README.md")" > "$OUT_DIR/README.md"
